title: Episodes
description: Tech Odisha Podcast | Odisha's 1st Technology Podcast
author: Tech Odisha Podcast
github: https://github.com/jnanadarshan
about: This is "Tech Odisha". Odisha's first ever Technology Podcast
disqus_shortname: https-odisha-top
google_analytics: UA-126633541-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/odishaFirstOfficial/"
    - icon: fa-twitter
      link: "https://www.twitter.com/omyOishaFirst/"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/jnanadarshan"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About TOP
      url: /about/
    - text: Odisha Podcast
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://jnanadarshan.github.io"
baseurl: "/tech.odisha.top"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
